pass the vars from the calling workflow

diff --git a/.github/workflows/ci-build-publish.yml b/.github/workflows/ci-build-publish.yml
--- a/.github/workflows/ci-build-publish.yml
+++ b/.github/workflows/ci-build-publish.yml
@@ -11,6 +11,10 @@ on:
         required: true
       PACT_BROKER_TOKEN:
         required: true
+      AZURE_APM_CLIENT_ID:
+        required: true
+      AZURE_TENANT_ID:
+        required: true
     inputs:
       is_release:
         required: false
@@ -237,29 +241,28 @@ jobs:
         run: |
           if [ -z "${{ secrets.AZURE_APM_CLIENT_ID }}" ]; then
             echo "Error: AZURE_APM_CLIENT_ID is not set"
-            exit 1
+#            exit 1
           else
             echo "AZURE_APM_CLIENT_ID is set"
           fi
           if [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then
             echo "Error: AZURE_TENANT_ID is not set"
-            exit 1
+#            exit 1
           else
             echo "AZURE_TENANT_ID is set"
           fi
-          if [ -z "${{ secrets.ACR_LOGIN_SERVER }}" ]; then
-            echo "Error: ACR_LOGIN_SERVER is not set"
-            exit 1
-          else
-            echo "ACR_LOGIN_SERVER is set"
-          fi
+#          if [ -z "${{ secrets.ACR_LOGIN_SERVER }}" ]; then
+#            echo "Error: ACR_LOGIN_SERVER is not set"
+##            exit 1
+#          else
+#            echo "ACR_LOGIN_SERVER is set"
+#          fi
 
       - name: Azure Login (OIDC)
         uses: azure/login@v2
         with:
           client-id: ${{ secrets.AZURE_APM_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          audience: ${{ secrets.ACR_LOGIN_SERVER }}
 
 #      - name: Log in to Azure Container Registry (OIDC)
 #        uses: azure/docker-login@v2
